name = "cap-http-workers-test"
workers_dev = true
compatibility_date = "2024-09-23"
main = "build/worker/shim.mjs"

[build]
command = "cargo install worker-build 2>/dev/null || true && worker-build --release"
