[providers.age]
type = "age"
recipients = ["age1el69e58ka4rsrkry3tupszv4lj2kpxw77qq4mcyaffft20sj4c2sx6vf39"]

[secrets]
AGE_SECRET_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeW1vR0JLZHZrM28xS1ZITkVGN1hoZXdhY1N0TVh6a3gzRTE3UFN6TUhzClJYVExGZjFBMWZNRlp0dHM3dGZFYmdZVE9YOGdOdm5BYkdtYktWa2U3cjAKLS0tIFFaL1JHMUM5cUlsRTdiY2MveTI0SjVCNndVVXB5T2owVElXVXhNeDRsSEUKxAOoKTLnEiQX3aA0MJ/6lO1jPTiw2MPMGL4Hl+fMH2LduqIkfF7P4imfbr1XxPuYPJ7HFDKWp+J30FbYYC5/kiC/XiIW8P40MKBpSuCJD7Io6JeP0CBqxHYw8v0sERouzmB6qbjLADT7Jw==" }
